name: Lint

on: [push]
jobs:
    flake8:
        runs-on: ubuntu-latest
        steps:
            - name: Setup python
              uses: actions/setup-python@v1
              with: 
                 python-version: 3.8.9
                 architecture: x64
            - name: Install poetry
              run: pip install poetry
